
package fr.adaming.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceTomcat", targetNamespace = "http://soap.adaming.fr/", wsdlLocation = "http://localhost:8080/03_a_WebService_JAX_WS_Tamcat/CalWebService?wsdl")
public class WebServiceTomcat
    extends Service
{

    private final static URL WEBSERVICETOMCAT_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICETOMCAT_EXCEPTION;
    private final static QName WEBSERVICETOMCAT_QNAME = new QName("http://soap.adaming.fr/", "WebServiceTomcat");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/03_a_WebService_JAX_WS_Tamcat/CalWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICETOMCAT_WSDL_LOCATION = url;
        WEBSERVICETOMCAT_EXCEPTION = e;
    }

    public WebServiceTomcat() {
        super(__getWsdlLocation(), WEBSERVICETOMCAT_QNAME);
    }

    public WebServiceTomcat(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICETOMCAT_QNAME, features);
    }

    public WebServiceTomcat(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICETOMCAT_QNAME);
    }

    public WebServiceTomcat(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICETOMCAT_QNAME, features);
    }

    public WebServiceTomcat(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceTomcat(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalWebService
     */
    @WebEndpoint(name = "MonWebServicePort")
    public CalWebService getMonWebServicePort() {
        return super.getPort(new QName("http://soap.adaming.fr/", "MonWebServicePort"), CalWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalWebService
     */
    @WebEndpoint(name = "MonWebServicePort")
    public CalWebService getMonWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.adaming.fr/", "MonWebServicePort"), CalWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICETOMCAT_EXCEPTION!= null) {
            throw WEBSERVICETOMCAT_EXCEPTION;
        }
        return WEBSERVICETOMCAT_WSDL_LOCATION;
    }

}
