
package fr.adaming.saop;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://saop.adaming.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroDinar", targetNamespace = "http://saop.adaming.fr/", className = "fr.adaming.saop.ConversionEuroDinar")
    @ResponseWrapper(localName = "conversionEuroDinarResponse", targetNamespace = "http://saop.adaming.fr/", className = "fr.adaming.saop.ConversionEuroDinarResponse")
    @Action(input = "http://saop.adaming.fr/BanqueService/conversionEuroDinarRequest", output = "http://saop.adaming.fr/BanqueService/conversionEuroDinarResponse")
    public double conversionEuroDinar(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "disBonjour", targetNamespace = "http://saop.adaming.fr/", className = "fr.adaming.saop.DisBonjour")
    @ResponseWrapper(localName = "disBonjourResponse", targetNamespace = "http://saop.adaming.fr/", className = "fr.adaming.saop.DisBonjourResponse")
    @Action(input = "http://saop.adaming.fr/BanqueService/disBonjourRequest", output = "http://saop.adaming.fr/BanqueService/disBonjourResponse")
    public String disBonjour();

}
